image: python:latest

stages:
  - test
  - deploy

test-prod:
  stage: test
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/btax
  before_script:
    - source /home/ubuntu/env/btax/bin/activate
    - source /home/ubuntu/env/btax/bin/postactivate
    - cd /home/ubuntu/www/btax/
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python manage.py check
  after_script:
    - source /home/ubuntu/env/btax/bin/predeactivate
  only:
    - master

deploy-prod:
  stage: deploy
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/btax
    GIT_STRATEGY: clone
  before_script:
    - source /home/ubuntu/env/btax/bin/activate
    - source /home/ubuntu/env/btax/bin/postactivate
    - cd /home/ubuntu/www/btax/
    - python manage.py migrate
  script:
    - supervisorctl restart btax
  after_script:
    - source /home/ubuntu/env/btax/bin/predeactivate
  only:
    - master

test-dev:
  stage: test
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/btax_dev
  before_script:
    - source /home/ubuntu/env/btax_dev/bin/activate
    - source /home/ubuntu/env/btax_dev/bin/postactivate
    - cd /home/ubuntu/www/btax_dev/
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python manage.py check
  after_script:
    - source /home/ubuntu/env/btax_dev/bin/predeactivate
  only:
    - development-btax

deploy-dev:
  stage: deploy
  variables:
    GIT_CLONE_PATH: $CI_BUILDS_DIR/btax_dev
  before_script:
    - source /home/ubuntu/env/btax_dev/bin/activate
    - source /home/ubuntu/env/btax_dev/bin/postactivate
    - cd /home/ubuntu/www/btax_dev/
    - python manage.py migrate
  script:
    - sudo supervisorctl restart btax_dev
  after_script:
    - source /home/ubuntu/env/btax_dev/bin/predeactivate
  only:
    - development-btax