# Generated by Django 3.2.5 on 2021-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210913_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='deletado',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
    ]
