# Generated by Django 3.2.5 on 2021-09-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confignfse',
            name='email_envio',
            field=models.BooleanField(default=False, verbose_name='Habilitar o envio de emails automaticamente, para todas as emissões realizadas por essa Empresa.'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='endereco_uf',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='simples_nacional',
            field=models.BooleanField(default=False, verbose_name='Optante do simples nacional?'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True, verbose_name='Sigla do Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo_bairro',
            field=models.CharField(blank=True, choices=[('bairro', 'Bairro'), ('bosque', 'Bosque'), ('chacara', 'Chácara'), ('conjunto', 'Conjunto'), ('desmembramento', 'Desmembramento'), ('distrito', 'Distrito'), ('favela', 'Favela'), ('fazenda', 'Fazenda'), ('gleba', 'Gleba'), ('horto', 'Horto'), ('jardim', 'Jardim'), ('loteamento', 'Loteamento'), ('nucleo', 'Núcleo'), ('parque', 'Parque'), ('residencial', 'Residencial'), ('sitio', 'Sítio'), ('tropical', 'Tropical'), ('vila', 'Vila'), ('zona', 'Zona'), ('centro', 'Centro'), ('setor', 'Setor')], max_length=15, null=True, verbose_name='Tipo do Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo_logradouro',
            field=models.CharField(choices=[('alameda', 'Alameda'), ('avenida', 'Avenida'), ('chacara', 'Chácara'), ('colonia', 'Colônia'), ('condominio', 'Condomínio'), ('estancia', 'Estância'), ('estrada', 'Estrada'), ('fazenda', 'Fazenda'), ('praca', 'Praça'), ('prolongamento', 'Prolongamento'), ('rodovia', 'Rodovia'), ('rua', 'Rua'), ('sitio', 'Sítio'), ('travessa', 'travessa'), ('vicinal', 'Vicinal')], max_length=15, verbose_name='Tipo do Logradouro'),
        ),
        migrations.AlterField(
            model_name='rps',
            name='config_nfse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rps', to='core.confignfse'),
        ),
    ]
