# Generated by Django 3.2.5 on 2021-09-27 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210926_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='conta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.conta'),
            preserve_default=False,
        ),
    ]
