# Generated by Django 3.2.5 on 2021-10-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_servico_id_integracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='cnae',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='codigo_cidade_incidencia',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='codigo_tributacao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='deducao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='deletado',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='descricao_cidade_incidencia',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='discriminacao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='ibpt',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='iss',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='responsavel_retencao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='retencao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tributavel',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tributos_federais_retidos',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor',
        ),
    ]
