# Generated by Django 3.2.5 on 2021-12-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211026_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='É o usuário principal da conta?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.conta'),
        ),
    ]
