# Generated by Django 3.2.5 on 2022-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_conta_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='id_cedente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Usuário TechnoSpeed'),
        ),
    ]
