# Generated by Django 3.2.5 on 2022-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_conta_id_cedente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='bitrix_dominio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dominio Bitrix24'),
        ),
        migrations.AddField(
            model_name='conta',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Refresh Token Bitrix24'),
        ),
    ]
