# Generated by Django 3.2.5 on 2021-09-30 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_alter_servico_id_integracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_emitente', models.CharField(max_length=20, verbose_name='CNPJ do Emitente')),
                ('operacao', models.IntegerField(choices=[(1, 'Emissão'), (2, 'Cancelamento')], verbose_name='Operação')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_resposta', models.DateTimeField(null=True, verbose_name='Data de Resposta')),
                ('status', models.IntegerField(choices=[(3, 'Enviar'), (4, 'Enviado'), (5, 'Aguardando'), (6, 'Retornado')], verbose_name='Status')),
                ('status_integracao_retorno', models.IntegerField(choices=[(7, 'Disponível'), (6, 'Retornado')], verbose_name='Status Integração Retorno')),
                ('payload_operacao', models.TextField(max_length=5120, null=True, verbose_name='Payload da Operação')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.conta')),
            ],
        ),
    ]
