# Generated by Django 3.2.5 on 2021-10-26 13:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20211026_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_id', models.CharField(max_length=50)),
                ('sacado_cpf_cnpj', models.CharField(max_length=20)),
                ('sacado_email', models.EmailField(max_length=150)),
                ('sacado_nome', models.CharField(max_length=200)),
                ('sacado_telefone', models.CharField(max_length=17)),
                ('sacado_celular', models.CharField(max_length=17)),
                ('sacado_endereco_logradouro', models.CharField(max_length=150)),
                ('sacado_endereco_numero', models.CharField(max_length=20)),
                ('sacado_endereco_complemento', models.CharField(max_length=50, null=True)),
                ('sacado_endereco_bairro', models.CharField(max_length=50)),
                ('sacado_endereco_cep', models.CharField(max_length=10)),
                ('sacado_endereco_cidade', models.CharField(max_length=100)),
                ('sacado_endereco_uf', models.CharField(max_length=2)),
                ('sacado_endereco_pais', models.CharField(default='Brasil', max_length=50)),
                ('titulo_valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('titulo_numero_documento', models.CharField(max_length=20)),
                ('titulo_data_vencimento', models.DateField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conta')),
            ],
        ),
    ]
