# Generated by Django 3.2.5 on 2021-12-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cobranca',
        ),
    ]
